use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "kebab-case")]
pub enum ExerciseType {
    Run,
    TrailRun,
    VirtualRun,
    Ride,
    GravelRide,
    MountainBikeRide,
    EBikeRide,
    EMountainBikeRide,
    VirtualRide,
    Velomobile,
    Handcycle,
    Swim,
    Walk,
    Hike,
    Snowshoe,
    AlpineSki,
    BackcountrySki,
    NordicSki,
    Snowboard,
    IceSkate,
    InlineSkate,
    Skateboard,
    Rowing,
    VirtualRow,
    Kayaking,
    Canoeing,
    StandUpPaddling,
    Surf,
    Windsurf,
    Kitesurf,
    Sail,
    RockClimbing,
    WeightTraining,
    Crossfit,
    Hiit,
    Elliptical,
    StairStepper,
    Yoga,
    Pilates,
    Workout,
    Golf,
    Soccer,
    Tennis,
    Squash,
    Racquetball,
    Badminton,
    Pickleball,
    TableTennis,
    Wheelchair,
    #[serde(other)]
    Unknown,
}

impl ExerciseType {
    pub fn icon_label(&self) -> (&'static str, &'static str) {
        match self {
            Self::Run => ("ph-person-simple-run", "Run"),
            Self::TrailRun => ("ph-person-simple-run", "Trail Run"),
            Self::VirtualRun => ("ph-person-simple-run", "Virtual Run"),
            Self::Ride => ("ph-bicycle", "Ride"),
            Self::GravelRide => ("ph-bicycle", "Gravel Ride"),
            Self::MountainBikeRide => ("ph-bicycle", "Mountain Bike"),
            Self::EBikeRide => ("ph-bicycle", "E-Bike Ride"),
            Self::EMountainBikeRide => ("ph-bicycle", "E-Mountain Bike"),
            Self::VirtualRide => ("ph-bicycle", "Virtual Ride"),
            Self::Velomobile => ("ph-bicycle", "Velomobile"),
            Self::Handcycle => ("ph-bicycle", "Handcycle"),
            Self::Swim => ("ph-waves", "Swim"),
            Self::Walk => ("ph-person-simple-walk", "Walk"),
            Self::Hike => ("ph-mountains", "Hike"),
            Self::Snowshoe => ("ph-mountains", "Snowshoe"),
            Self::AlpineSki => ("ph-mountains", "Alpine Ski"),
            Self::BackcountrySki => ("ph-mountains", "Backcountry Ski"),
            Self::NordicSki => ("ph-mountains", "Nordic Ski"),
            Self::Snowboard => ("ph-mountains", "Snowboard"),
            Self::IceSkate => ("ph-person-simple", "Ice Skate"),
            Self::InlineSkate => ("ph-person-simple", "Inline Skate"),
            Self::Skateboard => ("ph-person-simple", "Skateboard"),
            Self::Rowing => ("ph-boat", "Rowing"),
            Self::VirtualRow => ("ph-boat", "Virtual Row"),
            Self::Kayaking => ("ph-boat", "Kayaking"),
            Self::Canoeing => ("ph-boat", "Canoeing"),
            Self::StandUpPaddling => ("ph-waves", "Stand-Up Paddling"),
            Self::Surf => ("ph-waves", "Surf"),
            Self::Windsurf => ("ph-waves", "Windsurf"),
            Self::Kitesurf => ("ph-waves", "Kitesurf"),
            Self::Sail => ("ph-boat", "Sail"),
            Self::RockClimbing => ("ph-mountains", "Rock Climbing"),
            Self::WeightTraining => ("ph-barbell", "Weight Training"),
            Self::Crossfit => ("ph-barbell", "CrossFit"),
            Self::Hiit => ("ph-barbell", "HIIT"),
            Self::Elliptical => ("ph-person-simple", "Elliptical"),
            Self::StairStepper => ("ph-stairs", "Stair Stepper"),
            Self::Yoga => ("ph-person-simple", "Yoga"),
            Self::Pilates => ("ph-person-simple", "Pilates"),
            Self::Workout => ("ph-barbell", "Workout"),
            Self::Golf => ("ph-golf", "Golf"),
            Self::Soccer => ("ph-soccer-ball", "Soccer"),
            Self::Tennis => ("ph-tennis-ball", "Tennis"),
            Self::Squash => ("ph-tennis-ball", "Squash"),
            Self::Racquetball => ("ph-tennis-ball", "Racquetball"),
            Self::Badminton => ("ph-tennis-ball", "Badminton"),
            Self::Pickleball => ("ph-tennis-ball", "Pickleball"),
            Self::TableTennis => ("ph-tennis-ball", "Table Tennis"),
            Self::Wheelchair => ("ph-wheelchair", "Wheelchair"),
            Self::Unknown => ("ph-medal", "Exercise"),
        }
    }
}
